[package]
name = "lvm-sys"
version = "0.1.1"
authors = ["Chris Holcombe <xfactor973@gmail.com>"]
homepage = "https://github.com/cholcombe973/lvm-sys"
build = "build.rs"
description = "LVM FFI bindings"
license = "MIT"

[build-dependencies]
bindgen = "~0.40"

[dependencies]
